/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.epam;

import com.epam.day1.CollectorOfFoodPortion;
import com.epam.day1.DataWithFoodPackages;
import com.epam.day1.DataWithFoodPackagesFromFile;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        DataWithFoodPackages dataWithFoodPackages = new DataWithFoodPackagesFromFile();
        CollectorOfFoodPortion collectorOfFoodPortion = new CollectorOfFoodPortion();
        collectorOfFoodPortion.collectedPackegesOfFoodForReindeers(dataWithFoodPackages);
    }
}
