/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.epam;

import com.epam.day1.Statistics;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        Statistics statistics = new Statistics();
        System.out.println(statistics.getMaxValueOfCaloriesCarryingByOneReindeer());
        System.out.println(statistics.getMaxValueOfCaloriesCarryingByThreeReindeer());

    }
}
